{% set version = "7.5.0" %}

package:
  name: overrides
  version: {{ version }}

source:
  url: https://github.com/mkorpela/overrides/archive/refs/tags/{{ version }}.tar.gz
  sha256: e71ef4d5bfc78e3bc0347cd9c7a9e2dcd1a233011d6559b992bbc58a1d9a582e

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - typing_utils

test:
  imports:
    - overrides
  requires:
    - pytest
  source_files:
    - tests/
  commands:
    - pytest -v tests/ -k "not test_nested_typevar_in_signature"

about:
  home: https://github.com/mkorpela/overrides
  license: Apache-2.0
  license_family: APACHE
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: A decorator to automatically detect mismatch when overriding a method.
  description: A decorator to automatically detect mismatch when overriding a method.
  doc_url: https://github.com/mkorpela/overrides
  dev_url: https://github.com/mkorpela/overrides

extra:
  recipe-maintainers:
    - h-vetinari
    - nelson-liu
