{% set name = "overrides" %}
{% set version = "4.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9c14302dd56a444b47b237ca42430d2e691a6794d49fff9c977d05af4e1fc850

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - overrides

about:
  home: https://github.com/mkorpela/overrides
  license: Apache-2.0
  license_family: APACHE
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: A decorator to automatically detect mismatch when overriding a method.
  description: A decorator to automatically detect mismatch when overriding a method.
  doc_url: https://github.com/mkorpela/overrides
  dev_url: https://github.com/mkorpela/overrides

extra:
  recipe-maintainers:
    - nelson-liu
