{% set name = "overrides" %}
{% set version = "4.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 406fcc838cca66b45e0af989ef422e1d62bc38e6acdee820855213b9612bb963

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - overrides

about:
  home: https://github.com/mkorpela/overrides
  license: Apache-2.0
  license_family: APACHE
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: A decorator to automatically detect mismatch when overriding a method.
  description: A decorator to automatically detect mismatch when overriding a method.
  doc_url: https://github.com/mkorpela/overrides
  dev_url: https://github.com/mkorpela/overrides

extra:
  recipe-maintainers:
    - nelson-liu
